#!/usr/bin/env php
<?php

use Aura\Cli\CliFactory;
use Aura\Cli\Status;
use WyriHaximus\ApiClient\Tools\ResourceGenerator;

/**
 * Locate and load autoloader
 */
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

/**
 * Instance application
 */
$cliFactory = new CliFactory();
$cliContext = $cliFactory->newContext($GLOBALS);
$cliStdio = $cliFactory->newStdio();
$resourceGenerator = new ResourceGenerator($cliContext, $cliStdio);

/**
 * Run application
 */
try {
    $resourceGenerator->run();
} catch (Exception $e) {
    $message = $e->getMessage();
    $cliStdio->errln(str_pad(' ', strlen($message)));
    $cliStdio->errln($message);
    $cliStdio->errln(str_pad(' ', strlen($message)));

    exit(Status::USAGE);
}

exit(Status::SUCCESS);
